# 2차원 리스트
<img src="./images/2Dim.png" width="1800">

In [1]:
a = [[1, 2, 3, ], [4, 5, 6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [3]:
# 리스트 이름 = [[0] * 열 개수 for i in range(행 개수)]
data = [[0] * 5 for i in range(4)]
print(data)

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


# 외부 라이브러리를 커맨드 창이 아니라 Jupyter Notebook에서 설치하기
!pip install 라이브러리명 → '!'를 붙여서 pip install을 실행하면 된다.

In [5]:
# !pip install numpy
import numpy as np

In [7]:
npArray = np.array(data)
print(npArray)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [14]:
print(len(data))  # 행 개수
print(len(data[0]))  # 열 개수
# print(data.shape)   # AttributeError
print(npArray.shape)
print(npArray.shape[0])
print(npArray.shape[1])

4
5
(4, 5)
4
5


In [17]:
for i in range(len(data)):
    print(data[i])

[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]


In [2]:
def matrix(data):
    for i in range(len(data)):
        for j in range(len(data[0])):
            print('{:3d}'.format(data[i][j]), end=' ')
        print()

<img src="./images/2Dim_Zigzag.png" width="700">

In [38]:
row, col = map(int, input('2차원 리스트를 만들 행과 열의 개수: ').split())
data = [[0] * col for i in range(row)]
n = 0  # 리스트에 1씩 증가하며 채워질 숫자가 기억되는 변수
for i in range(len(data)):  # 행
    # 짝수행인지 홀수행인지 판단한다.
    if i % 2 == 0:
        # 짝수행은 왼쪽에서 오른쪽으로 숫자를 채운다.
        for j in range(len(data[i])):
            n += 1
            data[i][j] = n
        # ===== for j
    else:
        # 홀수행은 오른쪽에서 왼쪽으로 숫자를 채운다.
        for j in range(len(data[i]) - 1, -1, -1):
            n += 1
            data[i][j] = n
        # ===== for j
    # ===== if
# ===== for i

matrix(data)
# print(np.array(data))

  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20 
 40  39  38  37  36  35  34  33  32  31  30  29  28  27  26  25  24  23  22  21 
 41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60 
 80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65  64  63  62  61 
 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 
120 119 118 117 116 115 114 113 112 111 110 109 108 107 106 105 104 103 102 101 
121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 
160 159 158 157 156 155 154 153 152 151 150 149 148 147 146 145 144 143 142 141 
161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 
200 199 198 197 196 195 194 193 192 191 190 189 188 187 186 185 184 183 182 181 
201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 
240 239 238 237 236 235 234 233 232 231 230 229 228 227 226 225 224 223 222 221 
241 242 243 244 245 246 247 

In [39]:
row, col = map(int, input('2차원 리스트를 만들 행과 열의 개수: ').split())
data = [[0] * col for i in range(row)]
n = 0
start = 0   # 2차원 리스트에 숫자가 채워지기 시작하는 열 인덱스
end = col - 1   # 2차원 리스트에 숫자가 채워지는 마지막 열 인덱스
sw = 1  # start부터 end까지 증가값으로 사용할 변수

for i in range(row):
    # i = 0, sw = 1, j = range(0, 5, 1) → 0, 1, 2, 3, 4
    # i = 1, sw = -1, j = range(4, -1, -1) → 4, 3, 2, 1, 0
    # i = 2, sw = 1, j = range(0, 5, 1) → 0, 1, 2, 3, 4
    # i = 3, sw = -1, j = range(4, -1, -1) → 4, 3, 2, 1, 0
    for j in range(start, end + sw, sw):
        n += 1
        data[i][j] = n
    start, end = end, start
    sw *= -1

matrix(data)

  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20 
 40  39  38  37  36  35  34  33  32  31  30  29  28  27  26  25  24  23  22  21 
 41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60 
 80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65  64  63  62  61 
 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 
120 119 118 117 116 115 114 113 112 111 110 109 108 107 106 105 104 103 102 101 
121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 
160 159 158 157 156 155 154 153 152 151 150 149 148 147 146 145 144 143 142 141 
161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 
200 199 198 197 196 195 194 193 192 191 190 189 188 187 186 185 184 183 182 181 
201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 
240 239 238 237 236 235 234 233 232 231 230 229 228 227 226 225 224 223 222 221 
241 242 243 244 245 246 247 

In [3]:
row, col = map(int, input('2차원 리스트를 만들 행과 열의 개수: ').split())
data = [[0] * col for i in range(row)]
n = 0
start = [i for i in range(col)] # 왼쪽부터 오른쪽으로 진행하는 열 인덱스를 기억하는 리스트를 선언한다.
end = [i for i in range(col - 1, -1, -1)]   # 오른쪽부터 왼쪽으로 진행하는 열 인덱스를 기억하는 리스트를 선언한다.

for i in range(row):
    for j in start:
        n += 1
        data[i][j] = n
    # ===== for j
    start, end = end, start
# ===== for i

matrix(data)

  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20 
 40  39  38  37  36  35  34  33  32  31  30  29  28  27  26  25  24  23  22  21 
 41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60 
 80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65  64  63  62  61 
 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 
120 119 118 117 116 115 114 113 112 111 110 109 108 107 106 105 104 103 102 101 
121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 
160 159 158 157 156 155 154 153 152 151 150 149 148 147 146 145 144 143 142 141 
161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 
200 199 198 197 196 195 194 193 192 191 190 189 188 187 186 185 184 183 182 181 
201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 
240 239 238 237 236 235 234 233 232 231 230 229 228 227 226 225 224 223 222 221 
241 242 243 244 245 246 247 